const reward = [{lv:55, certSealPDown:1, certSealPUp:1, certSealBDown:1, certSealBUp:2, certSealGDown:0,certSealGUp:0,
    skillChipPDown:1, skillChipPUp:1, skillChipBDown:2, skillChipBUp:3, skillChipGDown:0,skillChipGUp:0,
    wEnginePDown:1, wEnginePUp:1, wEngineBDown:3, wEngineBUp:4, wEngineGDown:0,wEngineGUp:0,
    hdDataValue:5,
    invLogPDown:3, invLogPUp:4, invLogBDown:3, invLogBUp:4, invLogGDown:0,invLogGUp:0,
    energyModulePDown:4, energyModulePUp:5, energyModuleBDown:4, energyModuleBUp:5, energyModuleGDown:0,energyModuleGUp:0,
    platingAgentPDown:4, platingAgentPUp:5, platingAgentBDown:7, platingAgentBUp:8, platingAgentGDown:0,platingAgentGUp:0,
    dennys:25000},
{lv:50, certSealPDown:1, certSealPUp:1, certSealBDown:1, certSealBUp:2, certSealGDown:0,certSealGUp:0,
    skillChipPDown:1, skillChipPUp:1, skillChipBDown:2, skillChipBUp:3, skillChipGDown:0,skillChipGUp:0,
    wEnginePDown:1, wEnginePUp:1, wEngineBDown:3, wEngineBUp:4, wEngineGDown:0,wEngineGUp:0,
    hdDataValue:4,
    invLogPDown:3, invLogPUp:4, invLogBDown:3, invLogBUp:4, invLogGDown:0,invLogGUp:0,
    energyModulePDown:4, energyModulePUp:5, energyModuleBDown:4, energyModuleBUp:5, energyModuleGDown:0,energyModuleGUp:0,
    platingAgentPDown:4, platingAgentPUp:5, platingAgentBDown:7, platingAgentBUp:8, platingAgentGDown:0,platingAgentGUp:0,
    dennys:25000},
{lv:45, certSealPDown:0, certSealPUp:1, certSealBDown:3, certSealBUp:4, certSealGDown:0,certSealGUp:0,
    skillChipPDown:0, skillChipPUp:1, skillChipBDown:3, skillChipBUp:4, skillChipGDown:0,skillChipGUp:0,
    wEnginePDown:0, wEnginePUp:1, wEngineBDown:4, wEngineBUp:5, wEngineGDown:0,wEngineGUp:0,
    hdDataValue:4,
    invLogPDown:2, invLogPUp:3, invLogBDown:6, invLogBUp:7, invLogGDown:0,invLogGUp:0,
    energyModulePDown:3, energyModulePUp:4, energyModuleBDown:7, energyModuleBUp:8, energyModuleGDown:0,energyModuleGUp:0,
    platingAgentPDown:3, platingAgentPUp:4, platingAgentBDown:9, platingAgentBUp:10, platingAgentGDown:0,platingAgentGUp:0,
    dennys:22500},
{lv:40, certSealPDown:0, certSealPUp:1, certSealBDown:3, certSealBUp:4, certSealGDown:0,certSealGUp:0,
    skillChipPDown:0, skillChipPUp:1, skillChipBDown:3, skillChipBUp:4, skillChipGDown:0,skillChipGUp:0,
    wEnginePDown:0, wEnginePUp:1, wEngineBDown:4, wEngineBUp:5, wEngineGDown:0,wEngineGUp:0,
    hdDataValue:3,
    invLogPDown:2, invLogPUp:3, invLogBDown:6, invLogBUp:7, invLogGDown:0,invLogGUp:0,
    energyModulePDown:3, energyModulePUp:4, energyModuleBDown:7, energyModuleBUp:8, energyModuleGDown:0,energyModuleGUp:0,
    platingAgentPDown:3, platingAgentPUp:4, platingAgentBDown:9, platingAgentBUp:10, platingAgentGDown:0,platingAgentGUp:0,
    dennys:22500},
{lv:35, certSealPDown:0, certSealPUp:0, certSealBDown:2, certSealBUp:3, certSealGDown:2,certSealGUp:3,
    skillChipPDown:0, skillChipPUp:0, skillChipBDown:2, skillChipBUp:3, skillChipGDown:4,skillChipGUp:5,
    wEnginePDown:0, wEnginePUp:0, wEngineBDown:3, wEngineBUp:4, wEngineGDown:4,wEngineGUp:5,
    hdDataValue:3,
    invLogPDown:1, invLogPUp:2, invLogBDown:9, invLogBUp:10, invLogGDown:0,invLogGUp:0,
    energyModulePDown:2, energyModulePUp:3, energyModuleBDown:9, energyModuleBUp:10, energyModuleGDown:0,energyModuleGUp:0,
    platingAgentPDown:2, platingAgentPUp:3, platingAgentBDown:10, platingAgentBUp:11, platingAgentGDown:0,platingAgentGUp:0,
    dennys:20000},
{lv:30, certSealPDown:0, certSealPUp:0, certSealBDown:2, certSealBUp:3, certSealGDown:2,certSealGUp:3,
    skillChipPDown:0, skillChipPUp:0, skillChipBDown:2, skillChipBUp:3, skillChipGDown:4,skillChipGUp:5,
    wEnginePDown:0, wEnginePUp:0, wEngineBDown:3, wEngineBUp:4, wEngineGDown:4,wEngineGUp:5,
    hdDataValue:2,
    invLogPDown:1, invLogPUp:2, invLogBDown:9, invLogBUp:10, invLogGDown:0,invLogGUp:0,
    energyModulePDown:2, energyModulePUp:3, energyModuleBDown:9, energyModuleBUp:10, energyModuleGDown:0,energyModuleGUp:0,
    platingAgentPDown:2, platingAgentPUp:3, platingAgentBDown:10, platingAgentBUp:11, platingAgentGDown:0,platingAgentGUp:0,
    dennys:20000},
{lv:25, certSealPDown:0, certSealPUp:0, certSealBDown:1, certSealBUp:2, certSealGDown:4,certSealGUp:5,
    skillChipPDown:0, skillChipPUp:0, skillChipBDown:1, skillChipBUp:2, skillChipGDown:5,skillChipGUp:6,
    wEnginePDown:0, wEnginePUp:0, wEngineBDown:2, wEngineBUp:3, wEngineGDown:4,wEngineGUp:5,
    hdDataValue:2,
    invLogPDown:0, invLogPUp:0, invLogBDown:10, invLogBUp:11, invLogGDown:6,invLogGUp:7,
    energyModulePDown:0, energyModulePUp:0, energyModuleBDown:13, energyModuleBUp:14, energyModuleGDown:11,energyModuleGUp:12,
    platingAgentPDown:0, platingAgentPUp:0, platingAgentBDown:11, platingAgentBUp:12, platingAgentGDown:15,platingAgentGUp:16,
    dennys:15000},
{lv:20, certSealPDown:0, certSealPUp:0, certSealBDown:1, certSealBUp:2, certSealGDown:4,certSealGUp:5,
    skillChipPDown:0, skillChipPUp:0, skillChipBDown:1, skillChipBUp:2, skillChipGDown:5,skillChipGUp:6,
    wEnginePDown:0, wEnginePUp:0, wEngineBDown:2, wEngineBUp:3, wEngineGDown:4,wEngineGUp:5,
    hdDataValue:0,
    invLogPDown:0, invLogPUp:0, invLogBDown:10, invLogBUp:11, invLogGDown:6,invLogGUp:7,
    energyModulePDown:0, energyModulePUp:0, energyModuleBDown:13, energyModuleBUp:14, energyModuleGDown:11,energyModuleGUp:12,
    platingAgentPDown:0, platingAgentPUp:0, platingAgentBDown:11, platingAgentBUp:12, platingAgentGDown:15,platingAgentGUp:16,
    dennys:15000},
{lv:10, certSealPDown:0, certSealPUp:0, certSealBDown:0, certSealBUp:0, certSealGDown:9,certSealGUp:10,
    skillChipPDown:0, skillChipPUp:0, skillChipBDown:0, skillChipBUp:0, skillChipGDown:7,skillChipGUp:8,
    wEnginePDown:0, wEnginePUp:0, wEngineBDown:0, wEngineBUp:0, wEngineGDown:9,wEngineGUp:10,
    hdDataValue:0,
    invLogPDown:0, invLogPUp:0, invLogBDown:6, invLogBUp:7, invLogGDown:4,invLogGUp:5,
    energyModulePDown:0, energyModulePUp:0, energyModuleBDown:8, energyModuleBUp:9, energyModuleGDown:7,energyModuleGUp:8,
    platingAgentPDown:0, platingAgentPUp:0, platingAgentBDown:7, platingAgentBUp:8, platingAgentGDown:10,platingAgentGUp:11,
    dennys:10000},
];

export default reward;